name: Run tests

on:
  pull_request:
  push:

jobs:
  php-tests:
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.1, 8.0, 7.4]
        laravel: [9.*, 8.*, 6.*]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 6.*
            testbench: 4.*
        exclude:
          - laravel: 9.*
            php: 7.4
          - laravel: 8.*
            php: 8.1
          - laravel: 6.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: composer run phpunit
